### ISSUE TITLE
Does this really need `electrumsv_sdk` as a dependency?

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/simple-indexer#5]
This only really uses an unrelated to the SDK helper function in the actual code. It should be expected that  anyone running the scripts should have the SDK installed already.

![image](https://user-images.githubusercontent.com/32600614/141848026-d8fa9786-8587-495f-90df-8a7cb831700b.png)

**Comment by AustEcon** [comment]
Okay so what I can do is remove `electrumsv_sdk` from the requirements.txt and remove the usage of it from the `simple_indexer/server.py`... 

But are you okay if I leave the contrib folder as-is and assume that anyone using the contrib scripts will have electrumsv_sdk installed?

See: https://github.com/electrumsv/simple-indexer/pull/6

**Comment by rt121212121** [comment]
Yes, sounds fine.
